version: "3.9"
services:
  api:
    image: node:20.11
    command: yarn start:dev
    working_dir: /app
    volumes:
      - $PWD:/app
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "apppass"
      MYSQL_ROOT_PASSWORD: "rootpass"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
